service:
  name: twitter-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUTH_URL: ${self:custom.Auth.url}
    AUTH_ID: ${self:custom.Auth.id}
    AUTH_USERNAME: ${self:custom.Auth.username}
    AUTH_PASSWORD: ${self:custom.Auth.password}
    TWITTER_CONSUMER_KEY: ${self:custom.Twitter.consumerKey}
    TWITTER_CONSUMER_SECRET: ${self:custom.Twitter.consumerSecret}
    TWITTER_ACCESS_TOKEN_KEY: ${self:custom.Twitter.tokenKey}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.Twitter.tokenSecret}
      
functions:
  send:
    handler: dist/src/handlers/send.handler
    events:
      - http:
          method: POST
          path: /send/{email}

custom:
  Twitter:
    consumerKey: ${file(env.yml):Twitter.consumerKey}
    consumerSecret: ${file(env.yml):Twitter.consumerSecret}
    tokenKey: ${file(env.yml):Twitter.tokenKey}
    tokenSecret: ${file(env.yml):Twitter.tokenSecret}
  Auth:
    url: ${file(env.yml):Auth.url}
    id: ${file(env.yml):Auth.id}
    username: ${file(env.yml):Auth.username}
    password: ${file(env.yml):Auth.password}
  bundle:
    linting: false