service:
  name: twitter-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    GET_USERS_URL: ${self:custom.Users.url}
    TWITTER_CONSUMER_KEY: ${self:custom.Twitter.consumerKey}
    TWITTER_CONSUMER_SECRET: ${self:custom.Twitter.consumerSecret}
    TWITTER_ACCESS_TOKEN_KEY: ${self:custom.Twitter.tokenKey}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.Twitter.tokenSecret}
    REDIS_PORT: ${self:custom.Redis.port}
    REDIS_HOST: ${self:custom.Redis.host}
    REDIS_PASSWORD: ${self:custom.Redis.password}
    COGNITO_URL: ${self:custom.Cognito.url}
    COGNITO_AUTHORIZATION: ${self:custom.Cognito.authorization}
  iamRoleStatements:
    - ${file(resources/MailQueueIAM.yml):MailQueueIAM}
      
functions:
  send:
    handler: dist/src/handlers/send.handler
    timeout: 45
    events:
      - http:
          method: POST
          path: /send/{email}
          authorizer:
            arn: ${self:custom.Cognito.arn}
            scopes:
              - ${self:custom.Cognito.scopes}

  sendAll:
    handler: dist/src/handlers/sendAll.handler
    timeout: 45
    events:
      - schedule: rate(4320 minutes)

custom:
  Cognito:
    arn: ${file(env.yml):Cognito.arn}
    url: ${file(env.yml):Cognito.url}
    authorization: ${file(env.yml):Cognito.authorization}
    scopes: ${file(env.yml):Cognito.scopes}
  Users:
    url: ${file(env.yml):Users.url}
  Twitter:
    consumerKey: ${file(env.yml):Twitter.consumerKey}
    consumerSecret: ${file(env.yml):Twitter.consumerSecret}
    tokenKey: ${file(env.yml):Twitter.tokenKey}
    tokenSecret: ${file(env.yml):Twitter.tokenSecret}
  Redis:
    port: ${file(env.yml):Redis.port}
    host: ${file(env.yml):Redis.host}
    password: ${file(env.yml):Redis.password}
  MailQueue:
    arn: ${cf:mail-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:mail-service-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false