service:
  name: twitter-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    GET_USERS_URL: ${self:custom.Users.url}
    AUTH_URL: ${self:custom.Auth.url}
    AUTH_ID: ${self:custom.Auth.id}
    AUTH_USERNAME: ${self:custom.Auth.username}
    AUTH_PASSWORD: ${self:custom.Auth.password}
    TWITTER_CONSUMER_KEY: ${self:custom.Twitter.consumerKey}
    TWITTER_CONSUMER_SECRET: ${self:custom.Twitter.consumerSecret}
    TWITTER_ACCESS_TOKEN_KEY: ${self:custom.Twitter.tokenKey}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.Twitter.tokenSecret}
  iamRoleStatements:
    - ${file(resources/MailQueueIAM.yml):MailQueueIAM}
      
functions:
  send:
    handler: dist/src/handlers/send.handler
    events:
      - http:
          method: POST
          path: /send/{email}
          authorizer: ${self:custom.Authorizer.url}
  sendAll:
    handler: dist/src/handlers/sendAll.handler
    events:
      - schedule: rate(2880 minutes)

custom:
  Authorizer:
    url: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  Users:
    url: ${file(env.yml):Users.url}
  Twitter:
    consumerKey: ${file(env.yml):Twitter.consumerKey}
    consumerSecret: ${file(env.yml):Twitter.consumerSecret}
    tokenKey: ${file(env.yml):Twitter.tokenKey}
    tokenSecret: ${file(env.yml):Twitter.tokenSecret}
  Auth:
    url: ${file(env.yml):Auth.url}
    id: ${file(env.yml):Auth.id}
    username: ${file(env.yml):Auth.username}
    password: ${file(env.yml):Auth.password}
  MailQueue:
    arn: ${cf:mail-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:mail-service-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false