service:
  name: user-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: GET
          path: /user/create

custom:
  bundle:
    linting: false