service:
  name: user-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
  iamRoleStatements:
    - ${file(resources/UsersTableIAM.yml):UsersTableIAM}
    - ${file(resources/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}
  
functions:
  hello:
    handler: dist/handlers/subscribe.handler
    events:
      - http:
          method: POST
          path: /subscribe

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  MailQueue:
    arn: ${cf:mail-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:mail-service-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false