service:
  name: user-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    SEND_TWEETS_URL: ${self:custom.SendTweets.url}
    COGNITO_URL: ${self:custom.Cognito.url}
    COGNITO_REFRESH_TOKEN: ${self:custom.Cognito.refreshToken}
  iamRoleStatements:
    - ${file(resources/UsersTableIAM.yml):UsersTableIAM}
    - ${file(resources/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}
  
functions:
  subscribe:
    handler: dist/src/handlers/subscribe.handler
    events:
      - http:
          method: GET # to access the route through the browser
          path: /subscribe/{email}
  unsubscribe:
    handler: dist/src/handlers/unsubscribe.handler
    events:
      - http:
          method: GET # to access the route through the browser
          path: /unsubscribe/{email}
  active:
    handler: dist/src/handlers/active.handler
    events:
      - http:
          method: GET
          path: /active
          authorizer:
            arn: ${self:custom.Cognito.arn}

custom:
  Cognito:
    arn: ${file(env.yml):Cognito.arn}
    url: ${file(env.yml):Cognito.url}
    refreshToken: ${file(env.yml):Cognito.refreshToken}
  SendTweets:
    url: ${file(env.yml):SendTweets.url}
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  MailQueue:
    arn: ${cf:mail-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:mail-service-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false